apiVersion: v1
kind: Namespace
metadata:
  name: webbai
  labels:
    name: webbai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webbai
  name: resource-collector
  labels:
    app: resource-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-collector
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
      labels:
        app: resource-collector
    spec:
      serviceAccountName: resource-collector
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
      containers:
        - image: public.ecr.aws/p5v6t9h8/k8s-resource-collector:v0.3-7-gd8a3f95
          imagePullPolicy: Always
          name: resource-collector
          env:
            - name: CLIENT_ID
              value: ""
            - name: API_KEY
              value: ""
          command:
            - /app/collector
            - --data-dir # directory to store staged data
            - /app/data
            - --kube-api-qps # max qps from this client to kube api server
            - "20"
            - --kube-api-burst # max burst for throttle from this client to kube api server
            - "30"
          resources:
            requests:
              memory: 1000Mi
              cpu: 100m
            limits:
              memory: 2000Mi
              cpu: 200m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: webbai
  name: resource-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webbai-resource-collector
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - podtemplates
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingressclasses
      - ingresses
      - networkpolicies
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webbai-resource-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webbai-resource-collector
subjects:
  - kind: ServiceAccount
    name: resource-collector
    namespace: webbai
