apiVersion: v1
kind: Namespace
metadata:
  name: webbai
  labels:
    name: webbai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webbai
  name: resource-collector
  labels:
    app: resource-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-collector
  template:
    metadata:
      labels:
        app: resource-collector
    spec:
      serviceAccountName: resource-collector
      containers:
        - image: public.ecr.aws/p5v6t9h8/k8s-resource-collector:v0.1-6-ga308641
          imagePullPolicy: Always
          name: resource-collector
          command:
            - /app/collector
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: webbai
  name: resource-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webbai-resource-collector
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - resourcequotas
      - serviceaccounts
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingressclasses
      - ingresses
      - networkpolicies
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webbai-resource-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webbai-resource-collector
subjects:
  - kind: ServiceAccount
    name: resource-collector
    namespace: webbai
