apiVersion: v1
kind: Namespace
metadata:
  name: webbai
  labels:
    name: webbai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-collector
  namespace: webbai
  labels:
    app: resource-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-collector
  template:
    metadata:
      labels:
        app: resource-collector
    spec:
      containers:
        - image: public.ecr.aws/p5v6t9h8/k8s-resource-collector:v0.1-3-g5351724
          imagePullPolicy: Always
          name: resource-collector
          command:
            - /app/collector
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.2"